// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTeam struct {
	Name string `json:"name"`
}

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
