// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTeam struct {
	Name string `json:"name"`
}

type NewUser struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
